name: 'Workflow to deploy Production'

on:
  push:
    branches:
      - main

jobs: 
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Workflow name
        shell: bash
        run: |
          echo "Deploying Production...."
          sleep 300s

